baseurl = "/"
languageCode = "en-us"
title = "SiQ Blog"
theme = "hugo-lithium"
googleAnalytics = "UA-158606301-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/stuartiquinn"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/stuartiquinn"

[params]
    description = "An R Blog with Blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo_siq.png"
    width = 50
    height = 50
    alt = "Logo"

